# tomcat
server:
  port: 8002
spring:
  boot:
    admin:
      client:
        url: "http://localhost:8000"
  application:
    name: mango-backup
# backup datasource
mango:
  backup:
    datasource:
      host: 192.144.226.54
      userName: root
      password: tomtom
      database: mango
management:
  endpoints:
    web:
      exposure:
        include: "*"